<a href="https://colab.research.google.com/github/MathewNhari/Sendy-Logistics-Challenge/blob/master/Ensemble%20Method%20Saved%20at%2015.00%2007-09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Importing Libraries**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#**Importing Data**

In [ ]:
riders = pd.read_csv('Riders.csv')
SampleSubmission = pd.read_csv('SampleSubmission.csv')
Test_df = pd.read_csv('Test.csv')
Train_df = pd.read_csv('Train.csv', parse_dates= ['Placement - Day of Month'])
VariableDefinitions = pd.read_csv('VariableDefinitions.csv')

In [ ]:
VariableDefinitions

                                     Order No                Unique number identifying the order
0                                     User Id  Unique number identifying the customer on a pl...
1                                Vehicle Type  For this competition limited to bikes, however...
2                               Platform Type  Platform used to place the order, there are 4 ...
3                        Personal or Business                                      Customer type
4                    Placement - Day of Month                  Placement - Day of Month i.e 1-31
5                Placement - Weekday (Mo = 1)                   Placement - Weekday (Monday = 1)
6                            Placement - Time  Placement - Time - Time of day the order was p...
7                 Confirmation - Day of Month               Confirmation - Day of Month i.e 1-31
8             Confirmation - Weekday (Mo = 1)                Confirmation - Weekday (Monday = 1)
9                         Confirmation - Time  Confirmation - Time - Time of day the order wa...
10           Arrival at Pickup - Day of Month          Arrival at Pickup - Day of Month i.e 1-31
11       Arrival at Pickup - Weekday (Mo = 1)           Arrival at Pickup - Weekday (Monday = 1)
12                   Arrival at Pickup - Time  Time of day the the rider arrived at the locat...
13                      Pickup - Day of Month                     Pickup - Day of Month i.e 1-31
14                  Pickup - Weekday (Mo = 1)                      Pickup - Weekday (Monday = 1)
15                              Pickup - Time  Pickup - Time - Time of day the the rider pick...
16      Arrival at Destination - Day of Month        Arrival at Delivery - Day of Month i.e 1-31
17  Arrival at Destination - Weekday (Mo = 1)         Arrival at Delivery - Weekday (Monday = 1)
18              Arrival at Destination - Time  Arrival at Delivery Time - Time of day the rid...
19                              Distance (KM)            The distance from Pickup to Destination
20                                Temperature  Temperature at the time of order placement in ...
21               Precipitation in millimeters   Precipitation at the time of order placement ...
22                                 Pickup Lat                       Latitude of pick up location
23                                Pickup Long                      Longitude of pick up location
24                            Destination Lat                      Latitude of delivery location
25                           Destination Long                     Longitude of delivery location
26                                   Rider Id             ID of the Rider who accepted the order
27                Time from Pickup to Arrival  Time in seconds between 'Pickup' and 'Arrival ...
28                                        NaN                                                NaN
29                              Rider Metrics                                                NaN
30                                   Rider Id  Unique number identifying the rider (same as i...
31                               No_Of_Orders           Number of Orders the rider has delivered
32                                        Age  Number of days since the rider delivered the f...
33                             Average_Rating                        Average rating of the rider
34                              No_of_Ratings   Number of ratings the rider has received. Rat...

**Sample Submission**

In [ ]:
SampleSubmission.head(1)

         Order_No  Time from Pickup to Arrival
0  Order_No_19248                        567.0

In [ ]:
riders.head(1)

       Rider Id  No_Of_Orders   Age  Average_Rating  No_of_Ratings
0  Rider_Id_396          2946  2298            14.0           1159

In [ ]:
Train_df.head(1)

        Order No      User Id  ...      Rider Id  Time from Pickup to Arrival
0  Order_No_4211  User_Id_633  ...  Rider_Id_432                          745

[1 rows x 29 columns]

In [ ]:
Train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21201 entries, 0 to 21200
Data columns (total 29 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Order No                                   21201 non-null  object
 1   User Id                                    21201 non-null  object
 2   Vehicle Type                               21201 non-null  object
 3   Platform Type                              21201 non-null  int64
 4   Personal or Business                       21201 non-null  object
 5   Placement - Day of Month                   21201 non-null  object
 6   Placement - Weekday (Mo = 1)               21201 non-null  int64
 7   Placement - Time                           21201 non-null  object
 8   Confirmation - Day of Month                21201 non-null  int64
 9   Confirmation - Weekday (Mo = 1)            21201 non-null  int64
 10  Confirmation - Time                        21201 non-null  object
 11  Arrival at Pickup - Day of Month           21201 non-null  int64
 12  Arrival at Pickup - Weekday (Mo = 1)       21201 non-null  int64
 13  Arrival at Pickup - Time                   21201 non-null  object
 14  Pickup - Day of Month                      21201 non-null  int64
 15  Pickup - Weekday (Mo = 1)                  21201 non-null  int64
 16  Pickup - Time                              21201 non-null  object
 17  Arrival at Destination - Day of Month      21201 non-null  int64
 18  Arrival at Destination - Weekday (Mo = 1)  21201 non-null  int64
 19  Arrival at Destination - Time              21201 non-null  object
 20  Distance (KM)                              21201 non-null  int64
 21  Temperature                                16835 non-null  float64
 22  Precipitation in millimeters               552 non-null    float64
 23  Pickup Lat                                 21201 non-null  float64
 24  Pickup Long                                21201 non-null  float64
 25  Destination Lat                            21201 non-null  float64
 26  Destination Long                           21201 non-null  float64
 27  Rider Id                                   21201 non-null  object
 28  Time from Pickup to Arrival                21201 non-null  int64
dtypes: float64(6), int64(12), object(11)
memory usage: 4.7+ MB

In [ ]:
#Train_df = Train_df.drop(['Precipitation in millimeters'], axis= 1)
#Test_df = Test_df.drop(['Precipitation in millimeters'], axis= 1)

# Joining Tables

In [ ]:
dataset = pd.concat(objs=[Train_df, Test_df], axis=0)
dataset = dataset.merge(riders, on='Rider Id', how='left')

In [ ]:
#Train_df = Train_df.merge(riders, on='Rider Id', how='left')
#Test_df = Test_df.merge(riders, on='Rider Id', how='left')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 28268
Data columns (total 33 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Order No                                   28269 non-null  object
 1   User Id                                    28269 non-null  object
 2   Vehicle Type                               28269 non-null  object
 3   Platform Type                              28269 non-null  int64
 4   Personal or Business                       28269 non-null  object
 5   Placement - Day of Month                   28269 non-null  object
 6   Placement - Weekday (Mo = 1)               28269 non-null  int64
 7   Placement - Time                           28269 non-null  object
 8   Confirmation - Day of Month                28269 non-null  int64
 9   Confirmation - Weekday (Mo = 1)            28269 non-null  int64
 10  Confirmation - Time                        28269 non-null  object
 11  Arrival at Pickup - Day of Month           28269 non-null  int64
 12  Arrival at Pickup - Weekday (Mo = 1)       28269 non-null  int64
 13  Arrival at Pickup - Time                   28269 non-null  object
 14  Pickup - Day of Month                      28269 non-null  int64
 15  Pickup - Weekday (Mo = 1)                  28269 non-null  int64
 16  Pickup - Time                              28269 non-null  object
 17  Arrival at Destination - Day of Month      21201 non-null  float64
 18  Arrival at Destination - Weekday (Mo = 1)  21201 non-null  float64
 19  Arrival at Destination - Time              21201 non-null  object
 20  Distance (KM)                              28269 non-null  int64
 21  Temperature                                22466 non-null  float64
 22  Precipitation in millimeters               751 non-null    float64
 23  Pickup Lat                                 28269 non-null  float64
 24  Pickup Long                                28269 non-null  float64
 25  Destination Lat                            28269 non-null  float64
 26  Destination Long                           28269 non-null  float64
 27  Rider Id                                   28269 non-null  object
 28  Time from Pickup to Arrival                21201 non-null  float64
 29  No_Of_Orders                               28269 non-null  int64
 30  Age                                        28269 non-null  int64
 31  Average_Rating                             28269 non-null  float64
 32  No_of_Ratings                              28269 non-null  int64
dtypes: float64(10), int64(12), object(11)
memory usage: 7.3+ MB

# **Data Cleaning**

**Checking for Duplicates**

In [ ]:
#No duplicate Data On Test Data
def Check_duplicates(df):
  duplicates = df.duplicated(subset = ['Order No'], keep = False)
  return df[duplicates]

In [ ]:
#No duplicates 
#Train_duplicates = Check_duplicates(Train_df)
#Test_duplucates = Check_duplicates(Test_df)
duplucates = Check_duplicates(dataset)

**Changing into int data types

In [ ]:
dataset['Platform Type'] = dataset['Platform Type'].astype('object')
#Test_df['Platform Type'] = Test_df['Platform Type'].astype('object')       
#Train_df['Placement - Day of Month'] = Train_df['Placement - Day of Month'].astype('int')
dataset['Placement - Day of Month'] = dataset['Placement - Day of Month'].astype('int')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 28268
Data columns (total 33 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Order No                                   28269 non-null  object
 1   User Id                                    28269 non-null  object
 2   Vehicle Type                               28269 non-null  object
 3   Platform Type                              28269 non-null  object
 4   Personal or Business                       28269 non-null  object
 5   Placement - Day of Month                   28269 non-null  int64
 6   Placement - Weekday (Mo = 1)               28269 non-null  int64
 7   Placement - Time                           28269 non-null  object
 8   Confirmation - Day of Month                28269 non-null  int64
 9   Confirmation - Weekday (Mo = 1)            28269 non-null  int64
 10  Confirmation - Time                        28269 non-null  object
 11  Arrival at Pickup - Day of Month           28269 non-null  int64
 12  Arrival at Pickup - Weekday (Mo = 1)       28269 non-null  int64
 13  Arrival at Pickup - Time                   28269 non-null  object
 14  Pickup - Day of Month                      28269 non-null  int64
 15  Pickup - Weekday (Mo = 1)                  28269 non-null  int64
 16  Pickup - Time                              28269 non-null  object
 17  Arrival at Destination - Day of Month      21201 non-null  float64
 18  Arrival at Destination - Weekday (Mo = 1)  21201 non-null  float64
 19  Arrival at Destination - Time              21201 non-null  object
 20  Distance (KM)                              28269 non-null  int64
 21  Temperature                                22466 non-null  float64
 22  Precipitation in millimeters               751 non-null    float64
 23  Pickup Lat                                 28269 non-null  float64
 24  Pickup Long                                28269 non-null  float64
 25  Destination Lat                            28269 non-null  float64
 26  Destination Long                           28269 non-null  float64
 27  Rider Id                                   28269 non-null  object
 28  Time from Pickup to Arrival                21201 non-null  float64
 29  No_Of_Orders                               28269 non-null  int64
 30  Age                                        28269 non-null  int64
 31  Average_Rating                             28269 non-null  float64
 32  No_of_Ratings                              28269 non-null  int64
dtypes: float64(10), int64(12), object(11)
memory usage: 7.3+ MB

**Dropping columns not in test Data**

In [ ]:
def columnDrop(df,columns):
  df.drop(columns, axis=1,inplace=True)
  #df.set_index(['Order No'], inplace= True)
  return df

In [ ]:
Cols = ['Precipitation in millimeters']
dataset = columnDrop(dataset,Cols)
#Test_df = columnDrop(Test_df,Drop_Test_Cols)
#Train_df = columnDrop(Train_df,Drop_Train_Cols)

**Seperating Time**

In [ ]:
def timeconvert(df,Time):
    df[Time] = df[Time].astype('datetime64')
    return df

In [ ]:
Time_columns = ['Placement - Time', 'Confirmation - Time',
                'Arrival at Pickup - Time','Pickup - Time','Arrival at Destination - Time']
dataset = timeconvert(dataset,Time_columns)
#Train_df = timeconvert(Train_df,Time_columns)
#Test_df = timeconvert(Test_df,Time_columns)

**Taking Care of missing Data**

In [ ]:
from sklearn.impute import SimpleImputer

def missingData(df,columns):
  
  imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
  
  imputer.fit(df[columns])
  #mode_imputer.fit(df[mode_cols])
  df[columns] = imputer.transform(df[columns])
  #df[mode_cols] = mode_imputer.transform(df[mode_cols])
  return df

In [ ]:
columns = ['Temperature','Time from Pickup to Arrival']
dataset = missingData(dataset,columns)

In [ ]:
dataset['Arrival at Destination - Day of Month'] = dataset['Arrival at Destination - Day of Month'].astype('object')
dataset['Arrival at Destination - Weekday (Mo = 1)'] = dataset['Arrival at Destination - Weekday (Mo = 1)'].astype('object')

In [ ]:

mode_cols = ['Arrival at Destination - Day of Month','Arrival at Destination - Weekday (Mo = 1)',
             'Arrival at Destination - Time']
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(dataset[mode_cols])
dataset[mode_cols] = imputer.transform(dataset[mode_cols])

In [ ]:
dataset['Arrival at Destination - Day of Month'] = dataset['Arrival at Destination - Day of Month'].astype('int')
dataset['Arrival at Destination - Weekday (Mo = 1)'] = dataset['Arrival at Destination - Weekday (Mo = 1)'].astype('int')

In [ ]:
dataset.head(2)

         Order No       User Id  ... Average_Rating No_of_Ratings
0   Order_No_4211   User_Id_633  ...           13.8           549
1  Order_No_25375  User_Id_2285  ...           13.6            69

[2 rows x 32 columns]

In [ ]:
def splitDatetime(df,columns):
  for item in columns:
    #df[item+'_day'] = pd.to_datetime(df[item]).dt.day
    df[item+'_hour'] = pd.to_datetime(df[item]).dt.hour
    df[item+'_minutes'] = pd.to_datetime(df[item]).dt.minute
    df[item+'_seconds'] = pd.to_datetime(df[item]).dt.second
  df.drop(columns,axis=1, inplace = True)
  return df

In [ ]:
Time_columns = ['Placement - Time', 'Confirmation - Time',
                'Arrival at Pickup - Time','Pickup - Time','Arrival at Destination - Time']
dataset = splitDatetime(dataset,Time_columns)
#Test_df = SplitDatetime(Test_df,Time_columns)

In [ ]:
dataset.head(1)

        Order No  ... Arrival at Destination - Time_seconds
0  Order_No_4211  ...                                    55

[1 rows x 42 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28269 entries, 0 to 28268
Data columns (total 42 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Order No                                   28269 non-null  object
 1   User Id                                    28269 non-null  object
 2   Vehicle Type                               28269 non-null  object
 3   Platform Type                              28269 non-null  object
 4   Personal or Business                       28269 non-null  object
 5   Placement - Day of Month                   28269 non-null  int64
 6   Placement - Weekday (Mo = 1)               28269 non-null  int64
 7   Confirmation - Day of Month                28269 non-null  int64
 8   Confirmation - Weekday (Mo = 1)            28269 non-null  int64
 9   Arrival at Pickup - Day of Month           28269 non-null  int64
 10  Arrival at Pickup - Weekday (Mo = 1)       28269 non-null  int64
 11  Pickup - Day of Month                      28269 non-null  int64
 12  Pickup - Weekday (Mo = 1)                  28269 non-null  int64
 13  Arrival at Destination - Day of Month      28269 non-null  int64
 14  Arrival at Destination - Weekday (Mo = 1)  28269 non-null  int64
 15  Distance (KM)                              28269 non-null  int64
 16  Temperature                                28269 non-null  float64
 17  Pickup Lat                                 28269 non-null  float64
 18  Pickup Long                                28269 non-null  float64
 19  Destination Lat                            28269 non-null  float64
 20  Destination Long                           28269 non-null  float64
 21  Rider Id                                   28269 non-null  object
 22  Time from Pickup to Arrival                28269 non-null  float64
 23  No_Of_Orders                               28269 non-null  int64
 24  Age                                        28269 non-null  int64
 25  Average_Rating                             28269 non-null  float64
 26  No_of_Ratings                              28269 non-null  int64
 27  Placement - Time_hour                      28269 non-null  int64
 28  Placement - Time_minutes                   28269 non-null  int64
 29  Placement - Time_seconds                   28269 non-null  int64
 30  Confirmation - Time_hour                   28269 non-null  int64
 31  Confirmation - Time_minutes                28269 non-null  int64
 32  Confirmation - Time_seconds                28269 non-null  int64
 33  Arrival at Pickup - Time_hour              28269 non-null  int64
 34  Arrival at Pickup - Time_minutes           28269 non-null  int64
 35  Arrival at Pickup - Time_seconds           28269 non-null  int64
 36  Pickup - Time_hour                         28269 non-null  int64
 37  Pickup - Time_minutes                      28269 non-null  int64
 38  Pickup - Time_seconds                      28269 non-null  int64
 39  Arrival at Destination - Time_hour         28269 non-null  int64
 40  Arrival at Destination - Time_minutes      28269 non-null  int64
 41  Arrival at Destination - Time_seconds      28269 non-null  int64
dtypes: float64(7), int64(29), object(6)
memory usage: 9.3+ MB

# **Feature Engineering**

**Get Dummy Variables**

In [ ]:
def dummy_encoder(df, cols):
  dummies = pd.get_dummies(df,columns= cols,drop_first = True)
  merged = pd.concat([df,dummies],axis='columns')
  final = merged.drop(cols, axis = 1)
  return dummies

In [ ]:
cols = ['Platform Type','Personal or Business', 'Placement - Weekday (Mo = 1)',
        'Confirmation - Weekday (Mo = 1)','Pickup - Weekday (Mo = 1)','Vehicle Type','Rider Id','User Id',
        'Arrival at Pickup - Weekday (Mo = 1)','Arrival at Destination - Weekday (Mo = 1)']
dataset = dummy_encoder(dataset, cols)
#Test_df = dummy_encoder(Test_df, cols)
dataset.head(1)

        Order No  ...  Arrival at Destination - Weekday (Mo = 1)_7
0  Order_No_4211  ...                                            0

[1 rows x 4798 columns]

In [ ]:
#set Order number as index
dataset.set_index('Order No',inplace = True)

**Variable Selection by Correlation and Significance**

In [ ]:
dataset.head(1)

               Placement - Day of Month  ...  Arrival at Destination - Weekday (Mo = 1)_7
Order No                                 ...
Order_No_4211                         9  ...                                            0

[1 rows x 4797 columns]

In [ ]:
# Calculate correlations between predictor variables and the response variable
corrs = dataset.corr()['Time from Pickup to Arrival'].sort_values(ascending=False)

In [ ]:
from scipy.stats import pearsonr

# Build a dictionary of correlation coefficients and p-values
dict_cp = {}

column_titles = [col for col in corrs.index if col!= 'Time from Pickup to Arrival']
for col in column_titles:
    p_val = round(pearsonr(dataset[col], dataset['Time from Pickup to Arrival'])[1],6)
    dict_cp[col] = {'Correlation_Coefficient':corrs[col],
                    'P_Value':p_val}

df_cp = pd.DataFrame(dict_cp).T
df_cp_sorted = df_cp.sort_values('P_Value')
df_cp_sorted[df_cp_sorted['P_Value']<0.1]

                       Correlation_Coefficient   P_Value
Distance (KM)                         0.504879  0.000000
Rider Id_Rider_Id_576                -0.032608  0.000000
User Id_User_Id_3149                 -0.035708  0.000000
No_Of_Orders                         -0.035719  0.000000
Average_Rating                       -0.037551  0.000000
...                                        ...       ...
Rider Id_Rider_Id_211                -0.009830  0.098401
Rider Id_Rider_Id_445                -0.009813  0.098969
User Id_User_Id_1102                 -0.009806  0.099213
User Id_User_Id_1754                  0.009792  0.099692
User Id_User_Id_102                  -0.009788  0.099850

[712 rows x 2 columns]

In [ ]:
# Model building - Independent Variable (IV) DataFrame
X_names = list(df_cp[df_cp['P_Value'] < 0.05].index)
X = dataset[X_names]
#Test_data = Test[X_names]
# The dependent variable remains the same:
y = dataset['Time from Pickup to Arrival']

In [ ]:
X.head()

                Distance (KM)  ...  User Id_User_Id_393
Order No                       ...
Order_No_4211               4  ...                    0
Order_No_25375             16  ...                    0
Order_No_1899               3  ...                    0
Order_No_9336               9  ...                    0
Order_No_27883              9  ...                    0

[5 rows x 535 columns]

In [ ]:
# Create the correlation matrix
corr = X.corr()

# Find rows and columns where correlation coefficients > 0.9 or <-0.9
corr[np.abs(corr) > 0.9]

                                    Distance (KM)  ...  User Id_User_Id_393
Distance (KM)                                 1.0  ...                  NaN
Arrival at Destination - Time_hour            NaN  ...                  NaN
Destination Long                              NaN  ...                  NaN
Rider Id_Rider_Id_519                         NaN  ...                  NaN
User Id_User_Id_2982                          NaN  ...                  NaN
...                                           ...  ...                  ...
Pickup Lat                                    NaN  ...                  NaN
Rider Id_Rider_Id_515                         NaN  ...                  NaN
Destination Lat                               NaN  ...                  NaN
User Id_User_Id_633                           NaN  ...                  NaN
User Id_User_Id_393                           NaN  ...                  1.0

[535 rows x 535 columns]

In [ ]:
# As before, we create the correlation matrix
# and find rows and columnd where correlation coefficients > 0.9 or <-0.9
corr = X.corr()
r, c = np.where(np.abs(corr) > 0.9)

# We are only interested in the off diagonal entries:
off_diagonal = np.where(r != c)

# Show the correlation matrix rows and columns where we have highly correlated off diagonal entries:
corr.iloc[r[off_diagonal], c[off_diagonal]]

                                        Placement - Weekday (Mo = 1)_5  ...  Pickup - Weekday (Mo = 1)_6
Pickup - Weekday (Mo = 1)_5                                   1.000000  ...                    -0.120178
Pickup - Weekday (Mo = 1)_5                                   1.000000  ...                    -0.120178
Pickup - Weekday (Mo = 1)_5                                   1.000000  ...                    -0.120178
Placement - Weekday (Mo = 1)_5                                1.000000  ...                    -0.120178
Placement - Weekday (Mo = 1)_5                                1.000000  ...                    -0.120178
Placement - Weekday (Mo = 1)_5                                1.000000  ...                    -0.120178
Confirmation - Weekday (Mo = 1)_5                             1.000000  ...                    -0.120178
Confirmation - Weekday (Mo = 1)_5                             1.000000  ...                    -0.120178
Confirmation - Weekday (Mo = 1)_5                             1.000000  ...                    -0.120178
Arrival at Pickup - Weekday (Mo = 1)_5                        1.000000  ...                    -0.120178
Arrival at Pickup - Weekday (Mo = 1)_5                        1.000000  ...                    -0.120178
Arrival at Pickup - Weekday (Mo = 1)_5                        1.000000  ...                    -0.120178
Pickup - Weekday (Mo = 1)_2                                  -0.230847  ...                    -0.119067
Pickup - Weekday (Mo = 1)_2                                  -0.230847  ...                    -0.119067
Pickup - Weekday (Mo = 1)_2                                  -0.230847  ...                    -0.119067
Arrival at Pickup - Weekday (Mo = 1)_2                       -0.230847  ...                    -0.119067
Arrival at Pickup - Weekday (Mo = 1)_2                       -0.230847  ...                    -0.119067
Arrival at Pickup - Weekday (Mo = 1)_2                       -0.230847  ...                    -0.119067
Confirmation - Weekday (Mo = 1)_2                            -0.230847  ...                    -0.119067
Confirmation - Weekday (Mo = 1)_2                            -0.230847  ...                    -0.119067
Confirmation - Weekday (Mo = 1)_2                            -0.230847  ...                    -0.119067
Placement - Weekday (Mo = 1)_2                               -0.230847  ...                    -0.119067
Placement - Weekday (Mo = 1)_2                               -0.230847  ...                    -0.119067
Placement - Weekday (Mo = 1)_2                               -0.230847  ...                    -0.119067
Confirmation - Day of Month                                   0.004686  ...                    -0.005399
Confirmation - Day of Month                                   0.004686  ...                    -0.005399
Confirmation - Day of Month                                   0.004686  ...                    -0.005399
Pickup - Day of Month                                         0.004686  ...                    -0.005399
Pickup - Day of Month                                         0.004686  ...                    -0.005399
Pickup - Day of Month                                         0.004686  ...                    -0.005399
Arrival at Pickup - Day of Month                              0.004686  ...                    -0.005399
Arrival at Pickup - Day of Month                              0.004686  ...                    -0.005399
Arrival at Pickup - Day of Month                              0.004686  ...                    -0.005399
Placement - Day of Month                                      0.004691  ...                    -0.005396
Placement - Day of Month                                      0.004691  ...                    -0.005396
Placement - Day of Month                                      0.004691  ...                    -0.005396
Confirmation - Weekday (Mo = 1)_6                            -0.120178  ...                     1.000000
Confirmation - Weekday (Mo = 1)_6                            -0.120178  ...                     1.000000
Confirmation - Weekday (Mo = 1)_6                            -0.120178  ...                     1.000000
Arrival at Pickup - Weekday (Mo = 1)_6                       -0.120178  ...                     1.000000
Arrival at Pickup - Weekday (Mo = 1)_6                       -0.120178  ...                     1.000000
Arrival at Pickup - Weekday (Mo = 1)_6                       -0.120178  ...                     1.000000
Pickup - Weekday (Mo = 1)_6                                  -0.120178  ...                     1.000000
Pickup - Weekday (Mo = 1)_6                                  -0.120178  ...                     1.000000
Pickup - Weekday (Mo = 1)_6                                  -0.120178  ...                     1.000000
Placement - Weekday (Mo = 1)_6                               -0.120178  ...                     1.000000
Placement - Weekday (Mo = 1)_6                               -0.120178  ...                     1.000000
Placement - Weekday (Mo = 1)_6                               -0.120178  ...                     1.000000

[48 rows x 48 columns]

In [ ]:
#DropColumns = ['Pickup - Weekday (Mo = 1)_5', 'Placement - Weekday (Mo = 1)_5','Placement - Weekday (Mo = 1)_5',
#               'Confirmation - Weekday (Mo = 1)_5', 'Confirmation - Weekday (Mo = 1)_5', 'Confirmation - Weekday (Mo = 1)_2',
#               'Pickup - Weekday (Mo = 1)_2','Pickup - Weekday (Mo = 1)_2', 'Placement - Weekday (Mo = 1)_2',
#               'Placement - Weekday (Mo = 1)_2','Confirmation - Day of Month','Confirmation - Day of Month',
#               'Confirmation - Day of Month','Arrival at Pickup - Day of Month','Arrival at Pickup - Day of Month',
#               'Arrival at Pickup - Day of Month','Pickup - Day of Month','Pickup - Day of Month',
#               'Placement - Day of Month','Placement - Day of Month','Placement - Weekday (Mo = 1)_6',
#               'Pickup - Weekday (Mo = 1)_6','Pickup - Weekday (Mo = 1)_6','Confirmation - Weekday (Mo = 1)_6',
#               'Confirmation - Weekday (Mo = 1)_6','Rider Id_Rider_Id_83']#'Rider Id_Rider_Id_83'

In [ ]:
#X_data = X_data.drop(DropColumns,axis=1)
# = Test_df.drop(DropColumns, axis=1)

# Ensemble Method

**Feature Scaling**

In [ ]:
# import the scaling module
from sklearn.preprocessing import StandardScaler

In [ ]:
# create standardization object
scaler_X = StandardScaler()
scaler_y = StandardScaler()

In [ ]:
columns = ['Distance (KM)', 'Destination Long','Pickup Long']
# save standardized features into new variable
X[columns] = scaler_X.fit_transform(X[columns])
#y_data = np.array(y_data).reshape(-1,1)
y_data = np.array(y).reshape(-1,1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

**splitting features into test set and training set**

In [ ]:
# import train/test split module
from sklearn.model_selection import train_test_split

In [47]:
# split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.20,
                                                    random_state=1)

**Ridge Model**

In [48]:
from sklearn.linear_model import LinearRegression, Ridge

In [49]:
ridge = Ridge()
regressor = LinearRegression()

In [50]:
ridge.fit(X_train, y_train)
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
ridge_pred = ridge.predict(X_test)
regressor_pred = regressor.predict(X_test)

In [52]:
from sklearn.metrics import mean_squared_error
ridge_rmse = mean_squared_error(y_test, ridge_pred, squared= False)
regressor_rmse = mean_squared_error(y_test, regressor_pred, squared= False)

In [53]:
ridge_rmse

682.4640290054556

In [54]:
regressor_rmse

15819194.478447853

Building Decision Tree

In [55]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
reg_tree = DecisionTreeRegressor(max_depth=3)

In [56]:
#bst_reg = AdaBoostRegressor(base_estimator = reg_tree)
#bst_reg.fit(X_train,y_train)

reg_tree.fit(X_train,y_train)
#bst_pred = bst_reg.predict(X_test)
dt_pred = reg_tree.predict(X_test)

In [57]:
dt_rmse = mean_squared_error(y_test, dt_pred, squared= False)
bst_rmse = mean_squared_error(y_test, bst_pred, squared= False)

NameError: ignored

In [ ]:
bst_rmse

In [ ]:
dt_rmse

SVR Model

In [ ]:
#from sklearn.svm import SVR
#sv_reg = SVR(kernel='rbf', gamma='auto')
#sv_reg.fit(X_train,y_train)
#svr_pred = sv_reg.predict(X_test)

In [ ]:
#svr_rmse = mean_squared_error(y_test, svr_pred, squared= False)

In [ ]:
#svr_rmse

Lasso Model

In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.01)
lasso.fit(X_train, y_train)
y_pred = lasso.predict(X_test)

In [ ]:
lasso_rmse = mean_squared_error(y_test, y_pred, squared= False)
lasso_rmse

XGBoost model

In [ ]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

In [ ]:
xgb_pred = xgb.predict(X_test)

In [ ]:
xgb_rmse = mean_squared_error(y_test, y_pred, squared= False)

In [ ]:
xgb_rmse

Stacking method

In [ ]:
from sklearn.ensemble import StackingRegressor
models = [("DT",reg_tree),("SVR",sv_reg),("Ridge",ridge),("lasso",lasso),("xgb",xgb)]

In [ ]:
meta_learner_reg = LinearRegression()
s_reg = StackingRegressor(estimators=models, final_estimator=meta_learner_reg)

In [ ]:
s_reg.fit(X_train,y_train)

In [ ]:
s_reg_pred = s_reg.predict(X_test)

In [ ]:
meta_rmse = mean_squared_error(y_test, s_reg_pred, squared= False)

In [ ]:
meta_rmse